@url=http://localhost:3000
@json=content-type: application/json

###注册接口
post {{url}}/register
{{json}}

{
    "username":"admin",
    "password":"123456"
}

###登入接口
post {{url}}/login
{{json}}

{
    "username":"admin",
    "password":"123456"
}

###获取所有用户
get {{url}}/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYjZiMWY4MjcwZWEyNDBmOGRkM2RmYSIsImlhdCI6MTYwNTgxMTUxNn0.6oiWdVNOpyqny6VLCtXvgJSNwOc1P64RRhD2K_NqJvE